In [6]:
from openalgo import api
from database_main import get_database_manager
client = api(api_key='7773b590c743c9184fb1bb74830091a379f88c2035a2203e2b40d24cb2f86711', host='http://127.0.0.1:5000')

response = client.history(
    symbol="NIFTY13JAN2625500CE", 
    exchange="NFO", 
    interval="D", 
    start_date="2025-12-01", 
    end_date="2025-12-31"
    )
response

[2026-01-10 08:16:48] INFO in _client: HTTP Request: POST http://127.0.0.1:5000/api/v1/history "HTTP/1.1 200 OK"

             close    high     low     oi    open  volume
timestamp
2025-12-17  576.55  676.05  551.10   3900  580.00     144
2025-12-18  557.45  620.00  518.00   5070  539.00      42
2025-12-19  673.10  681.80  639.95   5395  640.00      11
2025-12-22  823.45  828.45  775.00   4680  775.00      23
2025-12-23  822.35  847.00  814.65   4290  845.00      19
2025-12-24  783.10  869.35  783.10   4680  845.80      93
2025-12-26  669.00  755.00  650.20  35165  755.00     640
2025-12-29  573.15  699.95  555.55  48425  670.15     380
2025-12-30  565.20  587.05  509.10  48230  525.00     835
2025-12-31  731.05  758.00  582.00  66300  600.00    1272

In [2]:

db_manager = get_database_manager()
df = db_manager.get_ohlcv_data('NIFTY13JAN2625800PE', 
'NFO', 'D', '2025-12-10', '2025-12-10', instrument_type="OPTIONS")
df
# df = db_manager.get_ohlcv_data('NIFTY', 'NSE_INDEX', 'D', '2025-12-01', '2025-12-31', instrument_type="SPOT")

[2026-01-10 08:13:05] WARNING in database_main: No data found for NIFTY13JAN2625800PE (NFO, D)

Empty DataFrame
Columns: []
Index: []

In [3]:
client.interval()

[2026-01-10 08:13:05] INFO in _client: HTTP Request: POST http://127.0.0.1:5000/api/v1/intervals "HTTP/1.1 200 OK"

{'data': {'days': ['D'],
  'hours': ['1h'],
  'minutes': ['1m', '3m', '5m', '10m', '15m', '30m'],
  'months': [],
  'seconds': [],
  'weeks': []},
 'status': 'success'}